[auth]
client-id = "(your client-id)"
client-secret = "(your client-secret)"
internal-redirect-url = "http://127.0.0.1:18444"
external-redirect-url = "https://website.com/authpage"

[config]
id-history-size = 1000
readline-history-size = 500
ls-history-size = 10
chunked-upload-size-threshold = 20971520
chunked-upload-num-threads = 2
rclone-remote-name = 'box'
representation-max-attempts = 15
representation-wait-time = 2.0  # In seconds

# When using the 'get' command with the -r, --representation flag, these aliases
# may be passed rather than the full representation name (as returned by 'repr').
representation-aliases = [
    ['png1024', 'png_paged_1024x1024'],
    ['png2048', 'png_paged_2048x2048'],
    ['etext', 'extracted_text'],
]

# These determine the default --max-name-length and --max-id-length for
# commands that accept those arguments, if they're not explicitly given.
#
# The value can be an integer or a string; if it is a string, it will be
# eval()'d and can make use of the 'cols' variable, which represents the number
# of columns of the terminal window.
#
# Ex:
#   default-max-name-length = 'cols / 2.2'
#   default-max-id-length = 10
#
default-max-name-length = 60
default-max-id-length = 8
