[auth]
client-id = "(your client-id)"
client-secret = "(your client-secret)"
internal-redirect-url = "http://127.0.0.1:18444"
external-redirect-url = "https://website.com/authpage"

[config]
id-history-size = 1000
readline-history-size = 500
ls-history-size = 10
chunked-upload-size-threshold = 20971520
chunked-upload-num-threads = 2
rclone-remote-name = 'box'
