[auth]
client-id = "(your client-id)"
client-secret = "(your client-secret)"
internal-redirect-url = "http://127.0.0.1:18444"
external-redirect-url = "https://website.com/authpage"

[config]
id-history-size = 500
chunked-upload-size-threshold = 20971520
